### ISSUE TITLE
separate building and launching of the application

### ISSUE THREAD

**Issue by kd3n1z** [KD3n1z/gitwatcher#1]
config should look like this:

```yaml
# default config
default:
  shell: bash
  args:
  - -c
  - $cmd
  build:
  # default type is 'execute-shell-command'
  # optional is false by default
  # you muts specify 'execute' field
  - execute: npm clean
    optional: true
  - execute: npm install
  - execute: npm run build
  
  # runs only if the build is successful
  launch: npm start

# config for 'windows'
windows:
  # indicates whether the application should close before building or before launching
  # default type is 'launch'
  shutdown-before: build
  build:
  # this copies 'default' build steps
  - type: copy-build-steps
    execute: default
  - execute: echo windows
  
  # copies 'default' launch command if not specified
# ...
```
